name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Cargo check
        run: cargo check --locked

      - name: Cargo test
        run: cargo test --locked

      - name: Cargo clippy
        run: cargo clippy --all-features --all-targets --lib --bins --tests --benches --examples

      - name: Cargo fmt
        run: cargo fmt --check
